language: en

pipeline:
- name: SpacyNLP
  model: "./custom_en_model"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: SpacyEntityExtractor
  dimensions: ["PERSON"]
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: EntitySynonymMapper
- name: CRFEntityExtractor

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20260102-110848-flush-brick
